from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel


class ErrorCode(StrEnum):
    SETTINGS_VALIDATION_FAILED = "SETTINGS_VALIDATION_FAILED"
    SETTINGS_READ_FAILED = "SETTINGS_READ_FAILED"
    SETTINGS_SAVE_FAILED = "SETTINGS_SAVE_FAILED"
    SESSION_RETRY_UNAVAILABLE = "SESSION_RETRY_UNAVAILABLE"
    SESSION_RETRY_FAILED = "SESSION_RETRY_FAILED"
    SESSION_READ_ONLY = "SESSION_READ_ONLY"
    SESSION_VALIDATION_FAILED = "SESSION_VALIDATION_FAILED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_READ_FAILED = "SESSION_READ_FAILED"
    SESSION_SAVE_FAILED = "SESSION_SAVE_FAILED"
    MODEL_REQUEST_FAILED = "MODEL_REQUEST_FAILED"
    MODEL_CAPABILITY_INSUFFICIENT = "MODEL_CAPABILITY_INSUFFICIENT"
    INVALID_AGENT_OUTPUT = "INVALID_AGENT_OUTPUT"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_ARGUMENT_INVALID = "TOOL_ARGUMENT_INVALID"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    TODO_VALIDATION_FAILED = "TODO_VALIDATION_FAILED"
    TODO_NOT_FOUND = "TODO_NOT_FOUND"
    TODO_SAVE_FAILED = "TODO_SAVE_FAILED"
    TODO_READ_FAILED = "TODO_READ_FAILED"
    IPC_METHOD_NOT_FOUND = "IPC_METHOD_NOT_FOUND"
    IPC_INVALID_REQUEST = "IPC_INVALID_REQUEST"
    RUN_CANCELLED = "RUN_CANCELLED"
    CONTEXT_TOO_LARGE = "CONTEXT_TOO_LARGE"
    FILE_UNAVAILABLE = "FILE_UNAVAILABLE"
    FILE_REFERENCE_INVALID = "FILE_REFERENCE_INVALID"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class WiseTodoError(BaseModel):
    code: ErrorCode
    message: str
    user_message: str
    retryable: bool = False
    details: dict[str, Any] | None = None
